### ISSUE TITLE
excuse me!

### ISSUE THREAD

**Issue by Danzo7** [jhcloos/jhcloos.github.io#8]
Hello sir,
 So I saw that you've watched all my repositories for some reason, and to be honest I'm  a bit concerned. And after seeing the confusing content that you have here and figure that you have watched so many people repositories I think it's a bit creepy. Can you please be clear on what you are doing exactly so I can sleep in pieces thanks!

**Comment by Abourass** [comment]
@Danzo7 Entirely agreed! This user is following all my stuff as well. How weird!

**Comment by DrKain** [comment]
It's definitely a bot. They're pulled in 5k followers and a fair bit of attention from curious users, that's reason enough. There was a user on last.fm recently who was doing something similar until the website enforced a limit. Something to brag about, I suppose
